- hosts: deepschool_host
  tasks:
    - name: create workdir
      file:
        path: '{{ playbook_dest }}'
        state: directory
        owner: '{{ ansible_user }}'
      tags: [ 'prepare' ]

    - name: create clean script
      template:
        dest: '{{ playbook_dest }}/clean.sh'
        src: 'templates/clean.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: run clean script
      command: "{{ playbook_dest }}/clean.sh"
      ignore_errors: true
      tags: [ 'clean' ]

