- hosts: deepschool_host
  tasks:
    - name: create workdir
      file:
        path: '{{ playbook_dest }}'
        state: directory
        owner: '{{ ansible_user }}'
      tags: [ 'prepare' ]

    - name: create init_file script
      template:
        dest: '{{ playbook_dest }}/init_file.sh'
        src: 'templates/init_file.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: create run script
      template:
        dest: '{{ playbook_dest }}/run.sh'
        src: 'templates/run.sh'
        mode: 0755
      tags: ['prepare']

    - name: init_file
      command: "{{ playbook_dest }}/init_file.sh"
      tags: [ 'run' ]

    - name: run
      command: "{{ playbook_dest }}/run.sh"
      ignore_errors: true
      tags: [ 'run' ]

