version: '3.7'

services:
  genres_app:
    image: ${IMAGE}
    hostname: genres
    ports:
      - ${APP_PORT}:5000

  prometheus:
    image: prom/prometheus:v2.27.1
    hostname: prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:7.5.7
    hostname: grafana
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter
    ports:
      - ${NODE_EXPORTER_PORT}:9100
    container_name: node_exporter
    hostname: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'


volumes:
  prometheus_data: {}
  grafana_data: {}
