- hosts: '{{ host }}'
  tasks:
    - name: create workdir
      file:
        path: '{{ playbook_dest }}'
        state: directory
        owner: '{{ ansible_user }}'
      tags: [ 'prepare' ]

    - name: copy grafana configs
      copy:
        src: '../../grafana'
        dest: '{{ playbook_dest }}'

    - name: copy prometheus configs
      copy:
        src: "../../prometheus"
        dest: '{{ playbook_dest }}'

    - name: create docker-compose
      template:
        dest: "{{ playbook_dest }}/docker-compose.yaml"
        src: "../../docker-compose.yaml"
        mode: 0755
      tags: ['prepare']

    - name: create pull script
      template:
        dest: '{{ playbook_dest }}/pull.sh'
        src: 'templates/pull.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: create run script
      template:
        dest: '{{ playbook_dest }}/run.sh'
        src: 'templates/run.sh'
        mode: 0755
      tags: ['prepare']

    - name: create destroy script
      template:
        dest: '{{ playbook_dest }}/destroy.sh'
        src: 'templates/destroy.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: create clean script
      template:
        dest: '{{ playbook_dest }}/clean.sh'
        src: 'templates/clean.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: pull docker image
      command: '{{ playbook_dest }}/pull.sh'
      register: echo_result
      tags: [ 'pull' ]

    - name: stop existing container
      command: "{{ playbook_dest }}/destroy.sh"
      ignore_errors: true
      register: echo_result
      tags: [ 'deploy' ]

    - name: run docker
      command: "{{ playbook_dest }}/run.sh"
      register: echo_result
      tags: [ 'deploy' ]

    - name: clean docker images and containers
      command: "{{ playbook_dest }}/clean.sh"
      ignore_errors: true
      register: echo_result
      tags: [ 'deploy' ]

