services:
  poster_analytics:
    cold_run: true
  poster_classifier:
    model_path: 'weights/genre_classifier.pt'
    device: ${oc.env:POSTER_DEVICE,'cpu'}
  rotate_classifier:
    model_path: 'weights/rotate_classifier.pt'
    device: ${oc.env:ROTATE_DEVICE,'cpu'}
